%% add_latex_style_to_bicycle_model_illustraction.m
%% 用于在visio画的二轮车图上增加公式样式的字母
%% 作者：HPC2H2
%% 日期：20240426

clc
clear
close all
I = imread('二轮车模型.png');
imtool(I);

figure;
imshow(I, 'InitialMagnification', 'fit');
x1 = 115; 
y1 = 590; 
x2 = 152;
y2 = 470;
x3 = 215;
y3 = 560;
x4 = 421;
y4 = 343;
x5 = 360;
y5 = 230;
x6 = 325;
y6 = 250;
x7 = 290;
y7 = 140;
x8 = 410;
y8 = 233;
x9 = 515;
y9 = 90;
x10 = 356;
y10 = 265;
angle_degree = 0; 
fontsize = 10; 
% 
text(x1, y1, '$O^g$', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree, ...
    'Color', 'black'); 
% 
text(x2, y2, '$Y^g$', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree, ...
    'Color', 'black'); 
% 
text(x3, y3, '$X^g$', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree, ...
    'Color', 'black'); 
%
text(x4, y4, '$L $', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree + 45, ...
    'Color', 'black'); 
% 
text(x5, y5, '$v_x $', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree + 45, ...
    'Color', '#00B0F0'); 
% 
text(x6, y6, '$v_y $', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree + 45, ...
    'Color', '#00B0F0'); 

text(x7, y7, '$\omega$', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree + 45, ...
    'Color', '#00B0F0'); 
% 
text(x8, y8, '$\varphi $', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree, ...
    'Color', 'black'); 
% 
text(x9, y9, '$\delta$', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree + 10, ...
    'Color', 'black'); 

text(x10, y10, '$O^g_v$', ...
    'Interpreter', 'latex', ...
    'FontSize', fontsize, ...
    'Rotation', angle_degree, ...
    'Color', 'black'); 

print('-dpng', 'bicycle_model.png');
